In [13]:
import warnings
warnings.simplefilter("ignore")
import pandas as pd
import re
from keras import Model
from keras.layers import Dense
from keras.layers import Dropout
from keras_pandas.Automater import Automater

In [2]:
df = pd.read_csv(r"../input/train.csv")
def add_title(cell): return re.search(' ([A-Za-z]+)\\.', cell).group(1)
df["Title"] = df.apply(lambda row: add_title(row["Name"]), axis=1)
df[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

In [23]:
auto = Automater(categorical_vars=['Pclass', 'Sex', 'Survived'],
                 numerical_vars=['Age', 'Fare', 'SibSp', 'Parch'],
                 text_vars=['Title', 'Cabin'],
                 response_var='Survived')
X, y = auto.fit_transform(df) # Transform the data set, using keras_pandas

x = auto.input_nub # Start model with provided input nub

x = Dense(16)(x) 
# x = Dropout(0.2)(x) 
# x = Dense(16, activation='relu')(x)
# x = Dense(16, activation='softmax')(x)
# x = Dense(16, activation='elu')(x)
# x = Dense(16, activation='selu')(x)
# x = Dense(16, activation='softplus')(x)
# x = Dense(16, activation='tanh')(x)
# x = Dense(16, activation='sigmoid')(x)
# x = Dense(16, activation='hard_sigmoid')(x)
# x = Dense(16, activation='linear')(x)
# x = Dense(16)(x) # Fill in your own hidden layers

x = auto.output_nub(x) # End model with provided output nub

model = Model(inputs=auto.input_layers, outputs=x)
model.compile(optimizer='Adam', loss=auto.loss, metrics=['accuracy'])

model.fit(X, y, epochs=25, validation_split=.2, verbose=2) # Train model

Train on 712 samples, validate on 179 samples
Epoch 1/25
 - 7s - loss: 0.5750 - acc: 0.6826 - val_loss: 0.4102 - val_acc: 0.8156
Epoch 2/25
 - 0s - loss: 0.4707 - acc: 0.7935 - val_loss: 0.4038 - val_acc: 0.8492
Epoch 3/25
 - 0s - loss: 0.4674 - acc: 0.8048 - val_loss: 0.3928 - val_acc: 0.8324
Epoch 4/25
 - 0s - loss: 0.4582 - acc: 0.8034 - val_loss: 0.3760 - val_acc: 0.8547
Epoch 5/25
 - 0s - loss: 0.4507 - acc: 0.8202 - val_loss: 0.3661 - val_acc: 0.8603
Epoch 6/25
 - 0s - loss: 0.4396 - acc: 0.8244 - val_loss: 0.3688 - val_acc: 0.8715
Epoch 7/25
 - 0s - loss: 0.4399 - acc: 0.8244 - val_loss: 0.3595 - val_acc: 0.8771
Epoch 8/25
 - 0s - loss: 0.4377 - acc: 0.8258 - val_loss: 0.3513 - val_acc: 0.8771
Epoch 9/25
 - 0s - loss: 0.4353 - acc: 0.8244 - val_loss: 0.3641 - val_acc: 0.8715
Epoch 10/25
 - 0s - loss: 0.4344 - acc: 0.8174 - val_loss: 0.3571 - val_acc: 0.8715
Epoch 11/25
 - 0s - loss: 0.4357 - acc: 0.8118 - val_loss: 0.3458 - val_acc: 0.8715
Epoch 12/25
 - 0s - loss: 0.4324 - acc: 0.8216 - val_loss: 0.3591 - val_acc: 0.8659
Epoch 13/25
 - 0s - loss: 0.4307 - acc: 0.8244 - val_loss: 0.3512 - val_acc: 0.8715
Epoch 14/25
 - 0s - loss: 0.4314 - acc: 0.8202 - val_loss: 0.3432 - val_acc: 0.8771
Epoch 15/25
 - 0s - loss: 0.4290 - acc: 0.8272 - val_loss: 0.3539 - val_acc: 0.8715
Epoch 16/25
 - 0s - loss: 0.4309 - acc: 0.8287 - val_loss: 0.3530 - val_acc: 0.8715
Epoch 17/25
 - 0s - loss: 0.4287 - acc: 0.8202 - val_loss: 0.3475 - val_acc: 0.8771
Epoch 18/25
 - 0s - loss: 0.4284 - acc: 0.8202 - val_loss: 0.3483 - val_acc: 0.8771
Epoch 19/25
 - 0s - loss: 0.4291 - acc: 0.8202 - val_loss: 0.3496 - val_acc: 0.8659
Epoch 20/25
 - 0s - loss: 0.4285 - acc: 0.8118 - val_loss: 0.3425 - val_acc: 0.8715
Epoch 21/25
 - 0s - loss: 0.4282 - acc: 0.8174 - val_loss: 0.3441 - val_acc: 0.8771
Epoch 22/25
 - 0s - loss: 0.4287 - acc: 0.8132 - val_loss: 0.3469 - val_acc: 0.8659
Epoch 23/25
 - 1s - loss: 0.4276 - acc: 0.8174 - val_loss: 0.3525 - val_acc: 0.8715
Epoch 24/25
 - 0s - loss: 0.4306 - acc: 0.8230 - val_loss: 0.3486 - val_acc: 0.8771
Epoch 25/25
 - 0s - loss: 0.4279 - acc: 0.8216 - val_loss: 0.3527 - val_acc: 0.8715